name: Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Buscar CÃ³digo
        uses: actions/checkout@v5

      - name: Login Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Imagem
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/modulo-3:latest .

      - name: Deploy Imagem
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/modulo-3:latest